PCDB_Rewrite/Models/RecipientView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PCDB_Rewrite.Models
{
    public class RecipientView
    {
        public string RecipientID { get; set; }
        public string Name { get; set; }
        public string Comments { get; set; }
    }

    public class RecipientViewFamily
    {
        public string RecipientID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Suffix { get; set; }
        public string RelatedTo { get; set; }
        public string Relationship { get; set; }
        public string Comments { get; set; }
    }
}

PCDB_Rewrite/Controllers/SubmitController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.ComTypes;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using PCDB_Rewrite.Helper;
using PCDB_Rewrite.Models;
using Microsoft.Extensions.Configuration;
using NLog;

namespace PCDB_Rewrite.Controllers
{
    public class SubmitController : Controller
    {
        private readonly pcdbContext _config;
        private readonly string _user;
        private readonly string userName;
        private readonly string _nonPhysicianPrefix;
        private readonly int _nonPhysicianValue;
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();


        public SubmitController(pcdbContext c, IHttpContextAccessor httpContextAccessor, IConfiguration configuration)
        {
            _config = c;
            _user = httpContextAccessor.HttpContext.User.Identity.Name;

            _nonPhysicianPrefix = configuration["AppSettings:NonPhysicianPrefix"];
            _nonPhysicianValue = Convert.ToInt32(configuration["AppSettings:NonPhysicianValue"]);
            // userName = Authentication.cleanUsername(_user);

            var config = new NLog.Config.LoggingConfiguration();
            var orFile = new NLog.Targets.FileTarget("logfile") { FileName = $"PCDBSubmissions{DateTime.Today:MM-dd-yy}.log" };
            config.AddRule(LogLevel.Info, LogLevel.Fatal, orFile);
            LogManager.Configuration = config;
        }
        
        [HttpPost]
        public IActionResult UpdateFamilyRecipient(IFormCollection collection)
        {
            try
            {
                var recipient = _config.TblRecipients.FirstOrDefault(x => x.RecipientIdPk == collection["RecipientID"].ToString());
                recipient.RecipientTitle = collection["Title"].ToString();
                recipient.RecipientFirstName = collection["firstName"].ToString();
                recipient.RecipientMi = collection["middleInitial"].ToString();
                recipient.RecipientLastName = collection["lastName"].ToString();
                recipient.RecipientSuffix = collection["suffixType"].ToString();
                recipient.RelationshipTypeIdFk = _config.TblRelationshipTypes.Where(x => x.RelationshipType == collection["relationshipType"].ToString()).Select(x => x.RelationshipTypeIdPk).FirstOrDefault();
                recipient.RecipientComments = collection["comments"].ToString();
                recipient.LastModifiedDate = DateTime.Now;
                recipient.LastModifiedUser = _user;

                _config.SaveChanges();
                
                return RedirectToAction("RecipientFamilyViewEdit", "Home",
                    new {recipientID = collection["recipientID"].ToString() });
            }
            catch (Exception e)
            {
                //Log update issue.
                _logger.Error("There was an issue Updating Family Recipient " + e.Message);
                return RedirectToAction("Error", "Home", new { error = "There was an issue Updating Family Recipient :: " + e.Message });
            }
        }

        [HttpPost]
        public IActionResult UpdateCourtesyDetails(IFormCollection collection)
        {
            try
            {
                var id = Convert.ToInt32(collection["Id"]);
                
                var bhEntity = collection["bhEntity"].ToString().Split(',');
                var hospitalIdFk = Convert.ToInt16(bhEntity[1]);

                var givenBy = collection["givenBy"].ToString().Split(',');

                int smtidFk;

                smtidFk = Convert.ToInt32(!string.IsNullOrEmpty(collection["inactiveGivenBy"]) ? collection["givenBy"].ToString() : givenBy[1]);

                var courtesyType = collection["CourtesyType"].ToString().Split(',');
                var courtesyTypeIdFk = Convert.ToInt16(courtesyType[1]);
                
                var c = _config.TblRecipientsCourtesies.FirstOrDefault(x => x.RecipientCourtesyIdPk == id);
                c.CourtesyTypeIdFk = courtesyTypeIdFk;
                c.HospitalIdFk = hospitalIdFk;
                c.DateGiven = Convert.ToDateTime(collection["dateGiven"].ToString());
                c.ValueGiven = Math.Round(Convert.ToDecimal(collection["value"].ToString()), 2);
                c.SmtidFk = smtidFk;

                c.Description = collection["description"].ToString();
                c.LastModifiedDate = DateTime.Now;
                c.LastModifiedUser = _user;

                _config.SaveChanges();
                
                return RedirectToAction("CourtesyList", "Home",
                    new { recipientID = collection["recipientId"].ToString() });
            }
            catch (Exception e)
            {
                //Log update issue.
                _logger.Error("There was an issue Updating Courtesy Details " + e.Message);
                return RedirectToAction("Error", "Home", new { error = "There was an issue Updating Courtesy Details :: " + e.Message });
            }
        }

        [HttpPost]
        public IActionResult AddNewCourtesy(IFormCollection collection)
        {
            try
            {
                var newCourtesy = new TblRecipientsCourtesy
                {
                    RecipientIdFk = collection["Id"].ToString(),
                    CourtesyTypeIdFk = Convert.ToInt16(collection["courtesyType"].ToString()),
                    HospitalIdFk = Convert.ToInt16(collection["bhEntity"].ToString()),
                    DateGiven = Convert.ToDateTime(collection["dateGiven"].ToString()),
                    ValueGiven = Convert.ToDecimal(collection["value"].ToString()),
                    SmtidFk = Convert.ToInt32(collection["givenBy"].ToString()),
                    Description = collection["description"].ToString(),
                    LastModifiedUser = _user,
                    LastModifiedDate = DateTime.Now,
                    RecordCreatedDate = DateTime.Now
                };

                _config.TblRecipientsCourtesies.Add(newCourtesy);

                _config.SaveChanges();

                return RedirectToAction("CourtesyList", "Home",
                    new { recipientID = collection["Id"].ToString() });
            }
            catch (Exception e)
            {
                //Log update issue.
                _logger.Error("There was an issue Inserting New Courtesy " + e.Message);

                return RedirectToAction("Error", "Home", new { error = "There was an issue Inserting New Courtesy :: " + e.Message });
            }
        }

        [HttpPost]
        public IActionResult AddNewFamilyRecipient(IFormCollection collection)
        {
            try
            {
                var fr = new TblRecipient();

                var id = collection["relatedToID"].ToString();
                var newRecipientId = "";

                var recipientCount = _config.TblRecipients.Count(x => x.RecipientIdPk.StartsWith(id));

                newRecipientId = id + "-" + (recipientCount);

                fr.RecipientIdPk = newRecipientId;
                fr.RecipientTitle = collection["titleType"].ToString();
                fr.RecipientFirstName = collection["firstName"].ToString();
                fr.RecipientMi = collection["middleInitial"].ToString();
                fr.RecipientLastName = collection["lastName"].ToString();
                fr.RecipientSuffix = collection["suffixType"].ToString();
                fr.RecipientComments = collection["description"].ToString();
                fr.RecipientIdFk = id;
                fr.RelationshipTypeIdFk = Convert.ToInt16(collection["relationshipType"].ToString());
                fr.LastModifiedUser = _user;
                fr.LastModifiedDate = DateTime.Now;
                fr.RecordCreatedDate = DateTime.Now;
                
                _config.TblRecipients.Add(fr);
                _config.SaveChanges();
                
                return RedirectToAction("RecipientFamilyAdd", "Home");
            }
            catch (Exception e)
            {
                //Log update issue.
                _logger.Error("There was an issue insert new Family Recipient " + e.Message);

                return RedirectToAction("Error", "Home", new { error = "There was an issue insert new Family Recipient :: " + e.Message });
            }
        }

        [HttpPost]
        public IActionResult AddNewNonPhysician(IFormCollection collection)
        {
            try
            {
                var np = new TblRecipient
                {
                    RecipientTitle = collection["titleType"].ToString(),
                    RecipientFirstName = collection["firstName"].ToString(),
                    RecipientMi = collection["middleInitial"].ToString(),
                    RecipientLastName = collection["lastName"].ToString(),
                    RecipientSuffix = collection["suffixType"].ToString(),
                    RecipientComments = collection["description"].ToString(),
                    LastModifiedUser = _user,
                    LastModifiedDate = DateTime.Now,
                    RecordCreatedDate = DateTime.Now,
                    RelationshipTypeIdFk = 14,
                    RecipientIdFk = "0"
                };


                //Generate Recipient ID PK
                
                var numGenerated = _config.TblRecipients.Count(x => x.RelationshipTypeIdFk == 14);
                var n = numGenerated + _nonPhysicianValue;

                var newRecipientId = _nonPhysicianPrefix + n;
                
                np.RecipientIdPk = newRecipientId;

                _config.TblRecipients.Add(np);
                _config.SaveChanges();

                return RedirectToAction("RecipientNSPAdd", "Home");
            }
            catch (Exception e)
            {
                //Log update issue.

PCDB_Rewrite/Views/Home/CourtesyAdd.cshtml
@model PCDB_Rewrite.Models.CourtesyAdd
@{
    ViewData["Title"] = "CourtesyAdd";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Physicians' Courtesy Database - Add a Courtesy</h1>
        </div>
    </div>
</div>

<br />

<form asp-controller="Submit" asp-action="AddNewCourtesy">
    @Html.HiddenFor(x => x.Id, new { @name = "id" })
    <div class="container">
        <br />
        <div class="row">
            <div class="col-md-4">
                @Html.ActionLink("Back", "CourtesyList", "Home", new { recipientID = Model.Id}, new {@class = "btn btn-info"})
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label>Recipient:</label>
                @Html.TextBoxFor(x => x.Recipient, new {Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "recipient"})
            </div>
            <div class="col-md-4">
                <label>Related To:</label>
                @Html.TextBoxFor(x => x.RelatedTo, new {Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "relatedTo"})
            </div>
            <div class="col-md-4">
                <label>Date Given:</label> <span class="redcolor">*</span>
                <input type="datetime" value="" class="form-control" id="datetimepicker1" name="dateGiven" required="required"/>
                <br />
                <span>If no date is selected before submitting, the date will default to the current date & time.</span>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-3">
                <label>BH Entity:</label> <span class="redcolor">*</span>
                <select name="bhEntity" id="bhentity" class="form-control" required="required">
                    <option value='0' selected disabled>Select BH Entity</option>
                    @foreach (var e in @ViewBag.BHEntities)
                    {
                        <option value='@e.Id.Trim()' name="bhEntity">@e.BHEntity</option>
                    }
                </select>
            </div>
            <div class="col-md-3">
                <label>Given By:</label> <span class="redcolor">*</span>
                <select name="givenBy" id="givenby" class="form-control" required="required">
                    <option value='0' selected disabled>Select Given By</option>
                    @foreach (var g in @ViewBag.GivenBy)
                    {
                        <option value='@g.Id.Trim()' name="f">@g.Name</option>
                    }
                </select>
            </div>
            <div class="col-md-3">
                <label>Courtesy Type:</label> <span class="redcolor">*</span>
                <select name="courtesyType" id="courtesyType" class="form-control" required="required">
                    <option value='0' selected disabled>Select Courtesy Type</option>
                    @foreach (var t in @ViewBag.CourtesyTypes)
                    {
                        <option value='@t.Id.Trim()' name="courtesyType">@t.CourtesyType</option>
                    }
                </select>
            </div>
            <div class="col-md-3">
                <label>Value:</label> <span class="redcolor">*</span>
                <input type="text" placeholder="0.00" class="form-control" id="value" name="value" required="required" onkeypress="return isNumberKey(this, event);"/>
            </div>
        </div>
        <br/>
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <label>Description (200 characters max):</label>
                <label class="redcolor" id="lblCharCount"></label>
                <textarea name="description" class="form-control" cols="40" rows="6" required="required" onkeyup="CommentsMaxLength(this, 200)" onkeydown="CommentsMaxLength(this, 200)" onchange="CommentsMaxLength(this, 200)"></textarea>
            </div>
            <div class="col-md-3"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <label style="color: red">* Required Fields</label>
                <br />
                <input type="submit" value="Save" class="btn btn-success btnStyle" />

                <br /><br />
                @Html.ActionLink("Cancel", "CourtesyList", "Home", new { recipientID = Model.Id }, new { @class = "btn btn-warning btnStyle" })

            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/js/courtesyAdd.js" asp-append-version="true"></script>
    <script src="~/js/commentsMaxLengthCheck.js" asp-append-version="true"></script>
}

PCDB_Rewrite/Views/Home/CourtesyViewEdit.cshtml
@model PCDB_Rewrite.Models.CourtesyDetails
@{
    ViewData["Title"] = "CourtesyViewEdit";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Physicians' Courtesy Database - View Courtesy</h1>
        </div>
    </div>
</div>
<br />
<form asp-controller="Submit" asp-action="UpdateCourtesyDetails">
    @Html.HiddenFor(x => x.BHEntity, new { @id = "selectedBhEntity" })
    @Html.HiddenFor(x => x.GivenBy, new { @id = "selectedGivenBy" })
    @Html.HiddenFor(x => x.CourtesyType, new { @id = "selectedCourtesyType" })
    @Html.HiddenFor(x => x.Id, new { name = "id" })
    @Html.HiddenFor(x => x.RecipientId, new { name = "recipientId" })
    <input type="hidden" value="@ViewBag.Year" name="year" />
    <div class="container">
        <br />
        <div class="row">
            <div class="col-md-4">
                @Html.ActionLink("Back", "CourtesyList", "Home", new { recipientID = Model.RecipientId }, new { @class = "btn btn-info" })
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label>Recipient:</label>
                @Html.TextBoxFor(x => x.Recipient, new { Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "recipient" })
            </div>
            <div class="col-md-4">
                <label>Related To:</label>
                @Html.TextBoxFor(x => x.RelatedTo, new { Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "relatedTo" })
            </div>
            <div class="col-md-4">
                <label>Date Given:</label> <span class="redcolor">*</span>
                @Html.TextBoxFor(x => x.DateGiven, new { Class = "form-control", type = "datetime", id = "datetimepicker1", placeholder = "", @name = "dateGiven", required = "required" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <label>BH Entity:</label> <span class="redcolor">*</span>
                <select name="bhEntity" id="bhentity" class="form-control" required="required">
                    @foreach (var e in @ViewBag.BHEntities)
                    {
                        <option value='@e.Id.Trim()' name="bhEntity">@e.BHEntity</option>
                    }
                </select>
            </div>
            <div class="col-md-4">
                @if (@Model.GivenByStatus == "A")
                {
                    <label>Given By:</label>
                    <span class="redcolor">*</span>
                    <select name="givenBy" id="givenby" class="form-control" required="required">
                        @foreach (var g in @ViewBag.GivenBy)
                        {
                            <option value='@g.Id.Trim()' name="f">@g.Name</option>
                        }
                    </select>
                }
                else
                {
                    <label>Given By:</label>
                    <span class="redcolor">(inactive)</span>
                    @Html.TextBoxFor(x => x.InactiveGivenBy, new { Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "relatedTo" })
                }
            </div>
            <div class="col-md-2"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-4">
                <label>Courtesy Type:</label> <span class="redcolor">*</span>
                <select name="courtesyType" id="courtesyType" class="form-control" required="required">
                    @foreach (var t in @ViewBag.CourtesyTypes)
                    {
                        <option value='@t.Id.Trim()' name="courtesyType">@t.CourtesyType</option>
                    }
                </select>
            </div>
            <div class="col-md-4">
                <label>Value:</label> <span class="redcolor">*</span>
                @Html.TextBoxFor(x => x.Value, new { Class = "form-control", placeholder = "", @name = "value", required = "required" })
            </div>
            <div class="col-md-2"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <label>Description: (200 characters max)</label>
                <label class="redcolor" id="lblCharCount"></label>
                @Html.TextAreaFor(x => x.Description, new { Class = "form-control", placeholder = "", @rows = 6, @name = "description", onkeyup = "CommentsMaxLength(this, 200)", onkeydown = "CommentsMaxLength(this, 200)", onchange = "CommentsMaxLength(this, 200)" })
            </div>
            <div class="col-md-3"></div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <label style="color: red">* Required Fields</label>
                <br />
                <input type="submit" value="Save" class="btn btn-success btnStyle" />
                <br /><br />
                @Html.ActionLink("Cancel", "CourtesyList", "Home", new { recipientID = Model.RecipientId }, new { @class = "btn btn-warning btnStyle" })

            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/js/courtesyViewEdit.js" asp-append-version="true"></script>
    <script src="~/js/commentsMaxLengthCheck.js" asp-append-version="true"></script>
}

PCDB_Rewrite/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Physicians' Courtesy Database - Recipient Search</h1>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-6 text-center">
            <input type="text" id="searchbox" class="form-control" placeholder="Search by Recipient Name" />
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-md-12">
            @foreach (var letter in ViewBag.Letters)
            {
                <a href="#@letter" style="padding-right: 2%; font-size: 1.25em;" onclick="GenerateResults('@letter')">@letter</a>
            }
        </div>
    </div>
</div>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <table id="pcdbTable" class="display" style="width: 100%">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Beaches Total</th>
                    <th>Downtown/WCH/South Totals</th>
                    <th>Nassau</th>
                    <th>PHS</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

@*<div class="container">
    <div id="loadingModal" class="modal">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4 text-center">
                <div class="modal-content">
                    <div class="row">
                        <div class="col-md-4"></div>
                        <div class="col-md-4">
                            <div id="loader"></div>
                        </div>
                        <div class="col-md-4"></div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>We are loading the Providers based on your request.</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</div>*@


@section scripts {
    <script src="~/js/recipientSearch.js" asp-append-version="true"></script>
}

PCDB_Rewrite/Views/Home/NotAuthorized.cshtml
@{
    ViewData["Title"] = "Not Authorized";
}

<div class="notauthorized">
    <img src="~/img/cancel.png" />
    <span>You are not authorized to see this page.</span>
    <div>Please contact an admin if you think this is in error or to get the necessary rights.</div>
</div>

PCDB_Rewrite/Views/Home/RecipientFamilyViewEdit.cshtml
@model PCDB_Rewrite.Models.RecipientViewFamily


@{
    ViewData["Title"] = "RecipientFamilyViewEdit";
}

<br />
<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Physicians' Courtesy Database - View Family Recipient</h1>
        </div>
    </div>
</div>
<br />
<form asp-controller="Submit" asp-action="UpdateFamilyRecipient">
    @Html.HiddenFor(x => x.Title, new { @id = "selectedTitle" })
    @Html.HiddenFor(x => x.Suffix, new { @id = "selectedSuffix" })
    @Html.HiddenFor(x =>x.Relationship, new {@id = "relationshipType"})
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <label>Recipient ID #:</label>
                @Html.TextBoxFor(x => x.RecipientID, new { Class = "form-control", placeholder = "", @readonly = "@readonly", @name = "recipientID" })
            </div>
            <div class="col-md-3">
                <label>Title:</label> <span class="redcolor">*</span>
                <select name="titleType" id="title" class="form-control" required="required">
                    @foreach (var title in @ViewBag.Titles)
                    {
                        <option value="@title.Title.Trim()" name="titleType">@title.Title.Trim()</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>First Name:</label> <span class="redcolor">*</span>
                @Html.TextBoxFor(x => x.FirstName, new { Class = "form-control", placeholder = "", required = "required", @name = "firstName" })
            </div>
            <div class="col-md-3">
                <label>Middle Initial:</label>
                @Html.TextBoxFor(x => x.MiddleInitial, new { Class = "form-control", placeholder = "", @name = "middleInitial" })
            </div>
            <div class="col-md-3">
                <label>Last Name:</label> <span class="redcolor">*</span>
                @Html.TextBoxFor(x => x.LastName, new { Class = "form-control", placeholder = "", required = "required", @name = "lastName" })
            </div>
            <div class="col-md-3">
                <label>Suffix:</label>
                <select name="suffixType" id="suffix" class="form-control">
                    @foreach (var suffix in @ViewBag.Suffixes)
                    {
                        <option value="@suffix.Suffix.Trim()" name="suffixType">@suffix.Suffix.Trim()</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label>Related To:</label>
                @Html.TextBoxFor(x => x.RelatedTo, new { Class = "form-control", placeholder = "", @readonly = "@readonly" })
            </div>
            <div class="col-md-3">
                <label>Relationship:</label> <span class="redcolor">*</span>
                <select name="relationshipType" id="relationship" class="form-control">
                    @foreach (var relationship in @ViewBag.Relationships)
                    {
                        <option value="@relationship.Relationship.Trim()" name="relationshipType">@relationship.Relationship.Trim()</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label>Comments: (200 characters max)</label>
                <label class="redcolor" id="lblCharCount"></label>
                @Html.TextAreaFor(x => x.Comments, new { Class = "form-control", placeholder = "", @rows = 6, @name = "comments", onkeyup = "CommentsMaxLength(this, 200)", onkeydown = "CommentsMaxLength(this, 200)", onchange = "CommentsMaxLength(this, 200)" })
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-4">
                <label style="color: red">* Required Fields</label>
                <br />
                <input type="submit" value="Save" class="btn btn-success btnStyle"/>
            </div>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/js/recipientFamilyViewEdit.js" asp-append-version="true"></script>
    <script src="~/js/commentsMaxLengthCheck.js" asp-append-version="true"></script>
}

PCDB_Rewrite/Views/Home/RecipientNSPAdd.cshtml
@{
    ViewData["Title"] = "RecipientNSPAdd";
}

<div class="container">
    <div class="row">
        <div class="col-md-12 text-center">
            <h1>Physicians' Courtesy Database - Add Non-Physician Recipient</h1>
        </div>
    </div>
</div>


<form asp-controller="Submit" asp-action="AddNewNonPhysician">
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <label>Title:</label> <span class="redcolor">*</span>
                <select name="titleType" id="title" class="form-control" required="required">
                    <option value='0' selected disabled>Select Title</option>
                    @foreach (var title in @ViewBag.Titles)
                    {
                        <option value="@title.Title.Trim()" name="titleType">@title.Title.Trim()</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3">
                <label>First Name:</label> <span class="redcolor">*</span>
                <input type="text" value="" name="firstName" class="form-control" required="required" />
            </div>
            <div class="col-md-3">
                <label>Middle Initial:</label>
                <input type="text" value="" name="middleInitial" class="form-control" />
            </div>
            <div class="col-md-3">
                <label>Last Name:</label> <span class="redcolor">*</span>
                <input type="text" value="" name="lastName" class="form-control" required="required" />
            </div>
            <div class="col-md-3">
                <label>Suffix:</label>
                <select name="suffixType" id="suffix" class="form-control">
                    <option value='0' selected disabled>Select Suffix</option>
                    @foreach (var suffix in @ViewBag.Suffixes)
                    {
                        <option value="@suffix.Suffix.Trim()" name="suffixType">@suffix.Suffix.Trim()</option>
                    }
                </select>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                <label>Comments (200 characters max):</label>
                <label class="redcolor" id="lblCharCount"></label>
                <textarea name="description" class="form-control" cols="40" rows="6" required="required" onkeyup="CommentsMaxLength(this, 200)" onkeydown="CommentsMaxLength(this, 200)" onchange="CommentsMaxLength(this, 200)"></textarea>
            </div>
            <div class="col-md-3"></div>
        </div>
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <label style="color: red">* Required Fields</label>
                <br />
                <input type="submit" value="Save" class="btn btn-success btnStyle" />
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</form>

@section scripts {
    <script src="~/js/commentsMaxLengthCheck.js" asp-append-version="true"></script>
}